language: ruby
rvm:
  - 2.2.6
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rspec
services:
  - postgresql
before_script:
  - psql -c 'create database bfr_webapp_db_test;' -U postgres
