class SampleData
  class RegionData
    module PlaceNames
      GROCERY_STORES = [
        "114 Grocery & Deli Incorporated",
        "1st Oriental Supermarket",
        "A & A Fine Foods",
        "A & G Fine Foods Incorporated",
        "A & P Food Stores",
        "A G Ferrari Foods",
        "Acme Markets",
        "African and Caribbean Supermarket",
        "AG Ferrari Foods",
        "Agro Foods",
        "Aguada Supermarket Incorporated",
        "Ajs Fine Foods",
        "Akins Natural Food",
        "AL & James Foods",
        "Al's Supermarket",
        "Albertsons",
        "ALDI",
        "All American Foods",
        "American Foods Group",
        "American Supermarket",
        "Americold Logistics",
        "Ameriqual Foods Inc.",
        "Ameristop Food Mart",
        "Amish Market Atlas Park",
        "Ammons Supermarket LLC",
        "Anderson Supermarket",
        "Andys Iga Foodliner",
        "Anshas West Indian Supermarket",
        "Apna Bazaar",
        "Apples Supermarket",
        "Arck Foods",
        "Arena Supermarket",
        "Arends Family Foods",
        "Aria Foods",
        "Arley Country Supermarket",
        "Armando's Supermarket",
        "Arteaga's Starlite Supermarket",
        "Artel Supermarket",
        "Associated Food Stores",
        "Atkinsons Market",
        "Austin Foods",
        "Azteca Grocery",
        "Azteca Mkt.",
        "Azteco Mkt.",
        "B & B Foods",
        "B & F Super Foods",
        "B & G Foods",
        "Babco Foods International",
        "Baker's",
        "Baldor Speciality Foods",
        "Bar S Foods",
        "Baraboo Sysco Food",
        "Bashas",
        "Basic American Foods",
        "Beit Brothers Supermarket",
        "Bel Air Supermarkets",
        "Ben E Keith Foods",
        "Benders Foods",
        "Benetti Foods",
        "Berner Foods Incorporated",
        "Better Brand Foods Inc.",
        "Bi lo Inc",
        "BI Rite Supermarket",
        "Bi-Lo",
        "BI-Rite Supermarket",
        "Big Apple Supermarket",
        "Big Bear Natural Foods",
        "Big M",
        "Big Saver Foods",
        "Big Sky Premium Meats & Specialty Foods",
        "Big Star Grocery",
        "Big Star Super Market",
        "Big Top Supermarket",
        "Big Town Foods",
        "Big Value Super Mkt.",
        "Big Y Foods",
        "Bil Mar Foods",
        "Bill & Eileen's Market",
        "Bill & Sons Super Market",
        "Bill Martin Foods",
        "Bills Family Foods",
        "Bills Shursave Supermarket",
        "Bills Super Market",
        "Billys Quick Stop & Farmers Market",
        "BJ's Wholesale Club",
        "Boardman Foods",
        "Bravo Supermarket",
        "Breaux Mart Supermarket",
        "Brookshire Brothers",
        "Brookville Supermarket",
        "Brothers Supermarket",
        "Broughton Foods",
        "Broulims Supermarket",
        "Broussards Supermarket Inc",
        "Bruce Foods Corporation",
        "Buche Foods",
        "Buehler's Buy-Low Supermarkets",
        "Bunge Foods",
        "Buschs Family Supermarket",
        "Butera Finer Foods",
        "Buy Rite Foods",
        "Buy Rite Supermarket",
        "Bybee Foods LLC",
        "C & R Super Market",
        "C Town",
        "Cal Maine Foods",
        "Cala Foods Inc",
        "Calderon Market",
        "California Creative Foods",
        "California Custom Foods",
        "California Family Foods",
        "Cardenas Foods",
        "Carrolls Foods Incorporated",
        "Carter's Supermarket",
        "Cash Wise Foods",
        "Cedar Food Market",
        "Centurion Foods LLC",
        "Ceriello Fine Foods",
        "Certified Grocers of III",
        "Chamberlins Natural Foods",
        "Chavez Supermarket",
        "Checo Supermarket",
        "Chestertown Natural Foods",
        "Chief Supermarkets",
        "City Market",
        "Costco",
        "County Market",
        "Crowley Foods",
        "Ctown",
        "Cub Foods",
        "Culloden Independent Supermarket Route 60",
        "Culloden Independent Supermarket",
        "Cumberland Farms",
        "D & B Foods",
        "D & D Super Mkt.",
        "D & J Supermarket Corp",
        "D & M Family Foods",
        "D & M Supermarket",
        "D & R Market",
        "D' Agostinos Supermarket",
        "Dabo Foods",
        "Dahls Foods",
        "Dakota Natural Foods Inc",
        "Danny's Fine Foods",
        "Dans Super Market",
        "Dans Supreme Supermarket",
        "Dash Markets",
        "Dave's Supermarket",
        "Davids Supermarket",
        "Davisco Foods",
        "Dawn Foods",
        "Daybreak Foods",
        "Dean Foods",
        "Delberts Supermarket",
        "Demoulas Supermarket",
        "Diamond Crystal Specialty Foods",
        "Diamond Supermarket",
        "Dicks Supermarket",
        "Dillon Stores",
        "Dominick's Finer Foods",
        "Donelans Supermarket",
        "Dot Foods",
        "Dover Super Market",
        "Down Home Foods",
        "Down to Earth Natural Foods",
        "Draegers Supermarket",
        "Dubois Super Foods",
        "E W James & Sons Supermarket",
        "Eagle Supermarket Corp.",
        "Earthlight Natural Foods",
        "Eastern Foods",
        "Eats Natural Foods",
        "Econo Foods",
        "El Ahorro",
        "Everyday",
        "Excel Supermarket",
        "Extra Supermarket",
        "F'real Foods",
        "Fairplay Finer Foods",
        "Fairway Finer Foods Inc.",
        "Fairway Finer Foods",
        "Fairway Food Market",
        "Fairway Foods Inc.",
        "Fairway Foods",
        "Fairway Wholesale",
        "Family Fare",
        "Family Foods",
        "Family Fresh Foods",
        "Fareway Stores Inc",
        "Farmers Foods",
        "Farmland Foods",
        "Fas Check Supermarket",
        "Fast Lane Foods",
        "Fast Track Foods",
        "Fastee Foods",
        "Fastop Foods Inc",
        "Fastpak Foods",
        "Fastrip Food Store",
        "Festival Foods",
        "Fiesta Foods",
        "Fine Fair Supermarket",
        "Flash Foods",
        "Fleck Foods Inc",
        "Floyds Supermarket",
        "Food 4 Less",
        "Food Bag",
        "Food Basket",
        "Food City",
        "Food Emporium",
        "Food Express",
        "Food Fair",
        "Food Giant",
        "Food Lion",
        "Food Roundup Supermarket",
        "Food World",
        "Foodarama Supermarkets",
        "Foodland",
        "Foodmart",
        "Foodmaster Supermarket",
        "Foodmax",
        "Foodsco",
        "Foodtown",
        "Foodway Supermarket",
        "Francescos Fabulous Foods LLC",
        "Franjo Supermarket",
        "Frank's Mkt.",
        "Fred Meyer",
        "Freedom Foods",
        "Freeland Foods",
        "Fresh and Easy Neighborhood",
        "Fresh And Natural Foods",
        "Fresh Pride Supermarkets",
        "Friendly Foods",
        "Frontera Foods",
        "Frys Food Stores",
        "Furrs Supermarket",
        "G & G Supermarket",
        "G & W Foods",
        "G U Family Market",
        "Gabriels Super Mkt",
        "Garcias Supermarket",
        "Geissler's Super Mkt.",
        "Gene's Heartland Foods",
        "Genuardis",
        "Gerritys",
        "Geyers Fresh Foods",
        "Giant Eagle",
        "Giant Food Store",
        "Giant Food",
        "Giant Markets Inc",
        "Glory Supermarket",
        "Goodings Supermarkets",
        "Grand Union Co",
        "Grants Supermarket",
        "Grauls Market",
        "Gristedes",
        "Grocery Fox",
        "Gruma Mission Foods",
        "Guadalajara Supermarket",
        "Guzman Grocery",
        "H & L Supermarket",
        "Haggen Food & Pharmacy",
        "Han Ah Reum Supermarket",
        "Handy Andy Supermarkets",
        "Hannaford",
        "Hanover Supermarket",
        "Happy Foods",
        "Harps Food Store",
        "Harris Teeter",
        "Harrys Fresh Foods",
        "Harvest -Foods",
        "Harvest Foods",
        "Harveys Super Market",
        "Hays Food Town",
        "Healthway Natural Foods",
        "Heartland Foods",
        "HEB",
        "Heinens",
        "Hen House",
        "Hillside Foods",
        "Holiday Foods",
        "Holiday Quality Foods",
        "Holland Market",
        "Hollys Town Super Market",
        "Hollywood Super Mkt.",
        "Homeland",
        "Homerun Foods",
        "Hometown Foods",
        "Horizon Foods",
        "Hornbachers Foods",
        "Hot Stuff Foods LLC",
        "Houchens Market",
        "Houghton Market",
        "Hung Vuong Super Market",
        "Hurricane Foods",
        "Huy Fong Foods Inc.",
        "Hy Klas Foods",
        "Hy Vee",
        "IBC Merita",
        "Ingles Market",
        "Island Pacific Supermarket",
        "Jack Rabbit Foods",
        "Jade Foods",
        "Jahnke Foods",
        "Jalisco Market",
        "Jamboree Foods",
        "James E W & Sons Supermarket",
        "Jardines Texas Foods",
        "Jaritza Supermarket",
        "Jennie O Foods",
        "Jensens Finest Foods",
        "Jerome Foods",
        "Jet Foods",
        "Jewel-Osco",
        "Jimmy Dean Foods",
        "Jimmy Foods",
        "Jimmy's Food Mart",
        "Jimmy's Foods",
        "Joseph Webb Foods",
        "Joy Bargain",
        "Joy Foods",
        "Joyti Supermarket",
        "Jubilee Foods",
        "Jumbo Foods",
        "Jw Fine Foods",
        "Kaiser Supermarket",
        "Kaneshic Supermarket",
        "Karina Grocery",
        "Karns Quality Foods",
        "Kash N Karry",
        "Kay Foods",
        "Kens Foods",
        "Kens Quik Foods",
        "Kensington Supermarket",
        "Kents Foods",
        "Kevins Great American",
        "Key Food",
        "Keystone Foods",
        "Kikos Supermarket",
        "Kim Market",
        "Kim Young",
        "King Brothers Super Market",
        "King Food",
        "King Kullen",
        "King Ranch Market",
        "King Soopers",
        "Kings Super Market",
        "Kleins Super Market",
        "Kmart Super Centers",
        "Koch Foods",
        "Kona Natural Foods",
        "Krauszers",
        "Kroger",
        "Kta Super Stores",
        "Kubiaks Family Foods",
        "Kumud Groceries",
        "Kwickie Flash Foods",
        "L & L Food Centers",
        "Labriola Leonard Foods",
        "Lake Mystic Super Market",
        "Lakeside Foods",
        "Lakewinds Natural Foods",
        "Landis Supermarket",
        "Landmark Foods",
        "Lawrence Bros Iga",
        "Leevers Supermarket",
        "Legacy Foods",
        "Leisure Time Foods",
        "Leprino Foods",
        "Lewis Food Town",
        "Lil Cricket",
        "Lil Peach",
        "Lobill Foods",
        "Logli Supermarkets",
        "Lowes Food",
        "Lucky's Supermarket",
        "Luihn Foods",
        "Mac's Fresh Market",
        "Mace Supermarkets",
        "Macs Market",
        "Made In Hawaii Foods",
        "Madison Foods",
        "Malone's Food Stores",
        "Mana Foods",
        "Mandros Imported Foods",
        "Marathon",
        "Marigold Foods",
        "Marino's Associated Foods",
        "Market Basket",
        "Marketplace Foods",
        "Mars Supermarket",
        "Marsh Supermarket",
        "Martin Preferred Foods",
        "Martin's Super Market",
        "Meijer",
        "Melmarkets Foodtown",
        "Met Foods",
        "Metal Supermarkets",
        "Metro Food Market",
        "Mi Bandera Supermarket",
        "Michael Foods",
        "Michoacam Supermarket",
        "Mission Foods",
        "Mojave Foods",
        "Morningstar Foods",
        "Mother Earth Natural Foods",
        "Neighborhood Market",
        "New Way Supermarket",
        "Newly Weds Food",
        "Newmans Foods",
        "Nice N Easy Grocery Shoppe",
        "Niemann Foods",
        "Nijiya Market",
        "Nikken Foods",
        "No Frills Supermarket",
        "Nob Hill Foods",
        "North Bay Foods",
        "North End Market",
        "Northgate Markets",
        "Northland Foods",
        "Nutricion Fundamental",
        "Oakridge Supermarket",
        "Occidental International Foods",
        "Old Dutch Foods",
        "One Stop Market",
        "Outpost Natural Foods",
        "Owens Supermarket",
        "P & C Foods",
        "P & T Supermarket",
        "P W Supermarkets",
        "Pacific Supermarket",
        "Pak'n Save",
        "Pal Supermarket",
        "Pantry Foods",
        "Paradise Foods",
        "Park N Shop",
        "Park Place Foods",
        "Patco Handy Stop",
        "Patel Brothers",
        "Pathmark",
        "Patricias Foods",
        "Patrick Murphy Market",
        "Pats Foods",
        "Paul's Supermarket",
        "Pavilions",
        "Paw Creek Foods Incorporated",
        "Pax Wholesome Foods",
        "Payfair Supermarket",
        "Payless Super Market",
        "Peachtree Natural Foods",
        "Pechin",
        "Pecks Market",
        "Pennant Foods",
        "Perez Supermarket",
        "Pic N Save",
        "Pic Pac Supermarket",
        "Pick Quick Foods",
        "Pick'n Save",
        "Pickles Olives Etc",
        "Pierces Supermarket",
        "Pierre Foods",
        "Piggly Wiggly",
        "Piglet Supermarket",
        "Pik Nik Foods",
        "Pinnacle Foods",
        "Pioneer Supermarket",
        "President Supermarket",
        "Price Chopper",
        "Price Cutter",
        "Price Less Foods",
        "Price Rite",
        "Publix",
        "Pw Supermarkets",
        "Qfc Quality Food Centers",
        "Quality Dairy Co.",
        "Quality Food Mart Super Markets",
        "Rainbow Foods",
        "Raley's Supermarkets & Drug Centers",
        "Ralphs Grocery Co.",
        "Rameys Supermarket",
        "Red Apple Food Marts",
        "Resers Fine Foods",
        "Reynolds Supermarket",
        "Riceland Foods",
        "Richdale Dairy Store",
        "Right Way Foods",
        "Roche Bros",
        "Rosauers Supermarket",
        "Rosco Supermarket",
        "Rouse's Supermarket",
        "Rowes Supermarkets",
        "Run In Foods",
        "Rush Hour Foods",
        "Sack N Save Foods",
        "Safeway",
        "Sam's Club",
        "Sav A Lot",
        "Save A Lot",
        "Save Mart Supermarket",
        "Saveland Supermarket",
        "SaveRite Grocery Warehouse",
        "Saverite Grocery Warehouse",
        "Saveway Foods",
        "Schnuck Markets",
        "Schratter Foods",
        "Schreiber Food Inc.",
        "Schwan's Fine Food",
        "Scolaris Food & Drug Co.",
        "Scotts Foods",
        "Seabra Supermarkets",
        "Seafood City Supermarket",
        "Seafood City Supermarkets",
        "Sedanos Supermarket",
        "Selecto Supermarket",
        "Seneca Foods",
        "Sentry Foods",
        "Shamrock Foods",
        "Shaw's Osco",
        "Shaws",
        "Sherwood Foods",
        "Shop and Go",
        "Shop N Save",
        "Shop Rite",
        "Shop Smart",
        "Shoppers Food",
        "Shoprite",
        "Shore Stop Food Stores",
        "Sigma Foods",
        "Smart & Final",
        "Smithfield Food",
        "Smiths Food & Drug Centers",
        "Snappy Foods",
        "Southern Family Foods",
        "Sparkle Super Markets",
        "Spee D Foods",
        "Sprint Foods",
        "Spruce Foods",
        "Star Market",
        "Stater Bros",
        "Stop & GO",
        "Stop & Save",
        "Stop & Shop",
        "Stop 1 Supermarket",
        "Stop Market",
        "Stop N Save",
        "Stop One Grocery",
        "Store 24",
        "Streetmans Supermarket",
        "Stremicks Heritage Foods",
        "Stripes",
        "Sturm Foods Inc",
        "Sugar Creek Stores",
        "Sullivans Foods",
        "Summer Fresh Supermarket",
        "Sun Hop Fat 1 Supermarket",
        "Sun Market",
        "Sun Mart Foods",
        "Sun Sang Supermarket",
        "Sun Valley Foods",
        "Sunbelt Foods",
        "Sunbelt Natural Foods",
        "Sundance Natural Foods",
        "Sunflower Farmers Market",
        "Sunflower Natural Foods Market",
        "Sunflower Natural Foods",
        "Sunflower Supermarket",
        "Sunland Foods",
        "Sunmart",
        "Sunny Food Store",
        "Sunny Fresh",
        "Sunny Groceries",
        "Sunny Ridge Supermarket",
        "Sunrise Food",
        "Sunrise Natural Foods Inc",
        "Sunrise Natural Foods",
        "Sunset Foods",
        "Sunshine Fine Foods",
        "Sunshine Foods",
        "Sunshine Market",
        "Sunshine Natural Foods",
        "Sunshine Supermarket",
        "Sunshine Supermarkets",
        "Super 1 Foods",
        "Super A Foods",
        "Super Bargain",
        "Super Bear Supermarket",
        "Super Food Store",
        "Super Food",
        "Super Fresh",
        "Super K Food Store",
        "Super One Foods",
        "Super S Foods",
        "Super Target",
        "Superfresh",
        "Superior Market",
        "Superior Supermarket",
        "Supervalu",
        "Supervalue",
        "Sure Winner Foods",
        "Sweetbay Supermarket",
        "Tawa Supermarket",
        "Tedeschi Food Shops",
        "Terry's Supermarket",
        "Terrys Supermarket",
        "Thriftway",
        "Times Super Market",
        "Tops Friendly Markets",
        "Tops Market",
        "Town & Country",
        "Trade Fair",
        "Trader Joe's",
        "Tradewinds Marketplace",
        "Tropical Supermarket",
        "Turkey Hill Mini Market",
        "Twin City Foods",
        "U Save Super Markets",
        "Ukrops Super Market",
        "Ultra Food's",
        "Ultra Foods",
        "United Supermarket",
        "Vallarta Supermarket",
        "Vons",
        "Wal-Mart Supercenter",
        "Waldbaums",
        "Wawa Food Markets",
        "Wayfield Foods",
        "Wegmans",
        "Weis Markets",
        "Wesselmans Supermarket",
        "Western Supermarket",
        "Westfarm Foods",
        "White Hen Pantry",
        "White Market",
        "Whites Fresh Foods",
        "Whole Foods Market",
        "Winco",
        "Winn Dixie"
      ]

      FOOD_BANKS = [
        "Akron-Canton Regional Foodbank",
        "Alameda County Community Food Bank",
        "All Faiths Food Bank",
        "America's Second Harvest of Coastal Georgia, Inc.",
        "America's Second Harvest of the Big Bend, Inc.",
        "Arkansas Foodbank",
        "Atlanta Community Food Bank",
        "Banco de Alimentos de Puerto Rico",
        "Blue Ridge Area Food Bank, Inc.",
        "Capital Area Food Bank",
        "Care and Share Food Bank",
        "Central Illinois Foodbank",
        "Central Pennsylvania Food Bank",
        "Central Texas Food Bank",
        "Channel One Food Bank",
        "Chattanooga Area Food Bank",
        "City Harvest",
        "Community Food Bank of Central Alabama",
        "Community Food Bank of Eastern Oklahoma",
        "Community Food Bank of Southern Arizona",
        "Community Food Bank",
        "Community Food Share",
        "Community Food Warehouse of Mercer County",
        "Community FoodBank of New Jersey",
        "Community Harvest Food Bank of Northeast Indiana, Inc.",
        "Connecticut Food Bank",
        "Dare to Care Food Bank",
        "East Texas Food Bank",
        "Eastern Illinois Foodbank",
        "El Pasoans Fighting Hunger",
        "Facing Hunger Foodbank",
        "Feeding America Eastern Wisconsin",
        "Feeding America Riverside | San Bernardino Counties",
        "Feeding America Southwest Virginia",
        "Feeding America West Michigan Food Bank",
        "Feeding America, Kentucky’s Heartland",
        "Feeding Northeast Florida",
        "Feeding San Diego",
        "Feeding South Dakota",
        "Feeding South Florida",
        "Feeding Tampa Bay",
        "Feeding the Gulf Coast",
        "Feeding the Valley Food Bank",
        "FeedMore",
        "FIND Food Bank",
        "Food Bank for Larimer County",
        "Food Bank for Monterey County",
        "Food Bank For New York City",
        "Food Bank for the Heartland",
        "Food Bank for Westchester",
        "Food Bank of Alaska, Inc.",
        "Food Bank of Central & Eastern North Carolina",
        "Food Bank of Central Louisiana",
        "Food Bank of Central New York",
        "Food Bank of Contra Costa and Solano",
        "Food Bank of Corpus Christi",
        "Food Bank of Delaware",
        "Food Bank of Eastern Michigan",
        "Food Bank of Iowa",
        "Food Bank of Lincoln, Inc.",
        "Food Bank of North Alabama",
        "Food Bank of Northeast Arkansas",
        "Food Bank of Northeast Georgia",
        "Food Bank of Northeast Louisiana",
        "Food Bank of Northern Indiana",
        "Food Bank of Northern Nevada",
        "Food Bank of Northwest Indiana, Inc.",
        "Food Bank of Northwest Louisiana",
        "Food Bank of South Central Michigan",
        "Food Bank of South Jersey",
        "Food Bank of the Albemarle",
        "Food Bank of the Golden Crescent",
        "Food Bank of the Rio Grande Valley, Inc.",
        "Food Bank of the Rockies",
        "Food Bank of the Southern Tier",
        "Food Bank of West Central Texas",
        "Food Bank of Western New York",
        "Food Finders Food Bank Inc.",
        "Food Gatherers",
        "Food Lifeline",
        "Food Share, Inc.",
        "Foodbank of Santa Barbara County",
        "Foodbank of Southeastern Virginia",
        "Foodlink, Inc.",
        "Foodshare",
        "Forgotten Harvest",
        "Fredericksburg Regional Foodbank",
        "Freestore Foodbank",
        "Gleaners Community Food Bank of Southeastern Michigan",
        "Gleaners Food Bank of Indiana, Inc.",
        "God's Pantry Food Bank, Inc.",
        "Golden Harvest Food Bank",
        "Good Shepherd Food Bank",
        "Great Plains Food Bank",
        "Greater Baton Rouge Food Bank",
        "Greater Berks Food Bank",
        "Greater Chicago Food Depository",
        "Greater Cleveland Food Bank, Inc.",
        "Greater Lansing Food Bank",
        "Greater Pittsburgh Community Food Bank",
        "H & J Weinberg NE PA Regional Food Bank",
        "HACAP Food Reservoir",
        "Harry Chapin Food Bank of Southwest Florida",
        "Harvest Hope Food Bank",
        "Harvest Regional Food Bank, Inc.",
        "Harvesters - The Community Food Network",
        "Hawaii Foodbank, Inc.",
        "High Plains Food Bank",
        "Hoosier Hills Food Bank",
        "Houston Food Bank",
        "Inter-Faith Food Shuttle",
        "Island Harvest",
        "Kansas Food Bank",
        "Long Island Cares, Inc.",
        "Los Angeles Regional Food Bank",
        "Lowcountry Food Bank",
        "MANNA FoodBank",
        "Maryland Food Bank",
        "Mid-Ohio Foodbank",
        "Mid-South Food Bank",
        "Middle Georgia Community Food Bank",
        "Mississippi Food Network",
        "Montana Food Bank Network",
        "Montgomery Area Food Bank, Inc.",
        "Mountaineer Food Bank",
        "New Hampshire Food Bank",
        "North Country Food Bank, Inc.",
        "North Texas Food Bank",
        "Northeast Iowa Food Bank",
        "Northern Illinois Food Bank",
        "Northwest Arkansas Food Bank",
        "Oregon Food Bank",
        "Ozarks Food Harvest",
        "Philabundance",
        "Placer Food Bank",
        "Redwood Empire Food Bank",
        "Regional Food Bank of Northeastern New York",
        "Regional Food Bank of Oklahoma",
        "Rhode Island Community Food Bank",
        "River Bend Food Bank",
        "River Valley Regional Food Bank",
        "Roadrunner Food Bank",
        "San Antonio Food Bank",
        "SE Ohio Foodbank",
        "Second Harvest Community Food Bank",
        "Second Harvest Food Bank of Central Florida",
        "Second Harvest Food Bank of East Central Indiana, Inc.",
        "Second Harvest Food Bank of East Tennessee",
        "Second Harvest Food Bank of Greater New Orleans and Acadiana",
        "Second Harvest Food Bank of Lehigh Valley and NE Pennsylvania",
        "Second Harvest Food Bank of Metrolina",
        "Second Harvest Food Bank of Middle Tennessee",
        "Second Harvest Food Bank of North Central Ohio",
        "Second Harvest Food Bank of Northeast Tennessee",
        "Second Harvest Food Bank of Northwest North Carolina",
        "Second Harvest Food Bank of Northwest Pennsylvania",
        "Second Harvest Food Bank of Orange County",
        "Second Harvest Food Bank of San Joaquin and Stanislaus Counties",
        "Second Harvest Food Bank of Santa Clara & San Mateo Counties",
        "Second Harvest Food Bank of Southeast North Carolina",
        "Second Harvest Food Bank of the Mahoning Valley",
        "Second Harvest Food Bank Santa Cruz County",
        "Second Harvest Foodbank of Clark, Champaign, & Logan Counties",
        "Second Harvest Foodbank of Southern Wisconsin",
        "Second Harvest Heartland",
        "Second Harvest Inland Northwest",
        "Second Harvest North Central Food Bank",
        "Second Harvest Northern Lakes Food Bank",
        "Second Harvest of South Georgia, Inc",
        "SF-Marin Food Banks",
        "Shared Harvest Foodbank",
        "South Plains Food Bank",
        "South Texas Food Bank",
        "Southeast Missouri Food Bank",
        "Southeast Texas Food Bank",
        "St. Louis Area Foodbank",
        "St. Mary's Food Bank Alliance",
        "Tarrant Area Food Bank",
        "Terre Haute Catholic Charities Foodbank",
        "The Food Bank for Central & Northeast Missouri",
        "The Food Bank of Western Massachusetts",
        "The FoodBank of Monmouth and Ocean Counties, Inc.",
        "The Foodbank, Inc.",
        "The Greater Boston Food Bank",
        "The Idaho Foodbank",
        "Three Square Food Bank",
        "Toledo Northwestern Ohio Food Bank",
        "Treasure Coast Food Bank",
        "Tri-State Food Bank, Inc.",
        "United Food Bank",
        "Utah Food Bank",
        "Vermont Foodbank",
        "Virginia Peninsula Foodbank",
        "Weld Food Bank",
        "West Ohio Food Bank",
        "West Texas Food Bank",
        "Westmoreland County Food Bank",
        "Wichita Falls Area Food Bank",
        "Worcester County Food Bank, Inc.",
        "Yuma Community Food Bank"
      ]
    end
  end
end
